### ISSUE TITLE
Configurable directory

### ISSUE THREAD

**Issue by mistic100** [KennethWussmann/hain-plugin-steam#1]
I am just starting using Hain, I don't know if plugins can store config.

But it would be great to be able to configure where games are stored (mine are not on the main hard drive).

Alternatively read Steam config to discover all possible locations (I don't know if it's possible, If we are lucky the info is in the registry).

**Comment by mistic100** [comment]
I found something in the file _%ProgramFiles%/Steam/config/config.vdf_ :
`InstallConfigStore.Software.Valve.Steam.BaseInstallFolder_1` is my default game folder.

**Comment by KennethWussmann** [comment]
Hey mistic100,

thanks for your feature-request. Allow to configure an own path should be easy to implement. 
I was trying to auto-discover the paths, obviously not quite well...
But it's always different. For example, I don't have any `BaseInstallFolder_1` entry in this config :confused:

I started using Node.js and JavaScript today, but I'll do my best :smile: 

thanks,
~ Kenneth

**Comment by mistic100** [comment]
Perhaps "BaseInstallFolder_1" is only here if the default directory differs from the standard one (where Steam.exe is located)

My current value is "B:\Program Files\Steam Games".

I don't have any games in "C:\Program Files (x86)\Steam\steamapps", everything is in "B:\Program Files\Steam Games\steamapps".

But my exe still resides in drive C: (SSD).

Good job if you started the language today :+1:

**Comment by KennethWussmann** [comment]
Okay, and `B:\Program Files\Steam Games\steamapps` contains `appmanifest_XXXX.acf` files?

Thanks :smile:

**Comment by mistic100** [comment]
yes they are here

**Comment by KennethWussmann** [comment]
Okay, I've added to feature to [configure own paths](https://github.com/KennethWussmann/hain-plugin-steam#configure-paths).

**Comment by mistic100** [comment]
Well... does not seem to work.

 - After installation it just says "You don't have any game". I cannot set the "steamapps" directory. This is certainly because there IS a "steamapps" folder in the default location, but empty. You should always allow to override the parameter.

- Now I manually edited the config file, providing only the path to "steamapps"
```json
{
  "steamapps_dir": "B:\Program Files\Steam Games\steamapps",
  "steam_dir": "",
  "recently_played": []
}
```
The plugins keeps saying "Please enter your **Steam** directory. So I did, but nothing happen, the config file is not modified.

- I edited the file again with both paths
```
{
  "steamapps_dir": "B:\Program Files\Steam Games\steamapps",
  "steam_dir": "C:\Program Files (x86)\Steam",
  "recently_played": []
}
```
And it keeps saying it can't find the Steam directory.

I'll take a look at the code.

**Comment by mistic100** [comment]
Sorry back-slashes must be escaped in the config file. Works better with 
```json
{
  "steamapps_dir": "B:\\Program Files\\Steam Games\\steamapps",
  "steam_dir": "C:\\Program Files (x86)\\Steam",
  "recently_played": []
}
```

Config from the GUI does not work though
