### ISSUE TITLE
Lag with many installed games

### ISSUE THREAD

**Issue by sethxd** [KennethWussmann/hain-plugin-steam#2]
Hey, I like this a lot! The only thing I'm running into is a big spike of lag when it first loads the list of games, because I have so many installed. I'm wondering if there would be a way to only display 10-15 at a time, whichever ones most closely match the query?

**Comment by KennethWussmann** [comment]
Hey sethxd,

thanks for your bug report. Version 1.2.0 now fixes your issue.

```
/steam
```
Now displays only your recently played games.

``` 
/steam <some-chars>
```
Only displays maximum ten results.

Sadly, I cannot fetch the recently played games directly from steam. So it only displays recently played games you start using my plugin.

Please delete `hain-plugin-steam` and reinstall.

thanks,
~ Kenneth

**Comment by sethxd** [comment]
Sounds great man, thanks for the quick response!
